FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY nuget-packages/ /root/.nuget/packages/
COPY ["Orders.Worker/Orders.Worker.csproj", "Orders.Worker/"]
COPY ["Orders.Contracts/Orders.Contracts.csproj", "Orders.Contracts/"]
RUN dotnet restore "Orders.Worker/Orders.Worker.csproj" --source /root/.nuget/packages

COPY . .
WORKDIR "/src/Orders.Worker"
RUN dotnet build "Orders.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Orders.Worker.csproj" -c Release -o /app/publish --source /root/.nuget/packages

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Orders.Worker.dll"]
