networks:
  reto3-network:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - reto3-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-api
    ports:
      - "9080:8080"
    networks:
      - reto3-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQHost=rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  payments-api:
    build:
      context: .
      dockerfile: Dockerfile.Payments
    container_name: payments-api
    ports:
      - "9081:8080"
    networks:
      - reto3-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    depends_on:
      - api

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.Gateway
    container_name: orders-gateway
    ports:
      - "7190:8080"
    networks:
      - reto3-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: Dockerfile.Worker
    container_name: orders-worker
    networks:
      - reto3-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQHost=rabbitmq
    depends_on:
      - rabbitmq
