networks:
  reto3-network:
    driver: bridge

services:

  orders-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-api
    ports:
      - "9080:8080"
    networks:
      - reto3-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3

  payments-api:
    build:
      context: .
      dockerfile: Dockerfile.Payments
    container_name: payments-api
    ports:
      - "9081:8080"
    networks:
      - reto3-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    depends_on:
      - orders-api
