apiVersion: apps/v1
kind: Deployment
metadata:
  name: reto3-api-deployment
  labels:
    app: reto3-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reto3-api
  template:
    metadata:
      labels:
        app: reto3-api
    spec:
      containers:
        - name: reto3-api
          image: reto3-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
